version: '3.8'

services:
  backend:
    build: ./backend
    container_name: poker_backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - poker_network

  frontend:
    build: ./frontend
    container_name: poker_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - poker_network

volumes:
  postgres_data:

networks:
  poker_network:
    driver: bridge
