spring.application.name=pokertable
# DB h2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
# Hibernate show sql
spring.jpa.show-sql=true
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.open-in-view=false
spring.security.filter.order=10
app.jwtSecret=767a48566f0f5bfb770fcbf1cf2e282546ec5465d9b86449132a8160709f85f9
app.jwtExpirationMs=86400000
server.port=${PORT:8080}
# u?yj .env
logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.security=DEBUG

